= Migration guide: platform 2.1.x to 3.0.x

[abstract]
--
Platform 3.0.0 binds to Across 4.0.0, which is built on top of Spring Boot 2.0.x and Spring Framework 5.0.x.
This is a major upgrade with *a lot of breaking changes*, mostly due to changes inside Spring dependencies.

NOTE: This guide is not a full overview of all new features and changes in Across or any of its modules.
It mainly focuses on upgrade related changes: usually breaking changes or new features that impact application/module configuration.
--

== General breaking changes

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Release-Notes

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Security-2.0

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide

=== Module developers

* Spring Boot property relaxed binding has changed, you must now use the canonical format in code when referencing a property
** see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#relaxed-binding

=== Property renaming

.Property prefix modifications
|===
|Module |Old prefix |New prefix

|Across Web
|`acrossWebModule`
|`across.web`

|===

=== Spring libraries

* Several Spring Data `Repository` interfaces have been modified.
Certain often used methods have been removed altogether and replaced with new alternatives (with a different signature).
For example `findOne(id)` has been replaced by `findById(id)` and now returns an `Optional`.

* Hibernate upgrades to 5.2, see migration guide: https://github.com/hibernate/hibernate-orm/blob/5.2/migration-guide.adoc

== Auto-configuration support

* `across.configuration` has been dropped in favour of `across-configuration.yml` which allows more advanced configuration

== Modules

=== AcrossHibernateModule

* some properties (`default-timeout`) have been changed of type, a duration is now sometimes required (eg. 5s instead of 5)

