[[whats-new]]
= Migration guide: platform 5.0.x to 5.1.x

:docs-across-base-url: xref:across:
:docs-asm-ahm-url-3_0_0: xref:hibernate-jpa-module::index.adoc#_3_0_0_release
:docs-asm-em-url-3_0_0: xref:entity-module::releases/3.x.adoc#3-0-1
:docs-asm-awm-url-3_0_0: xref:admin-web-module::index.adoc#_3_0_1_release
:docs-asm-bum-url-2_0_0: xref:bootstrap-ui-module::releases/2.x.adoc#2-0-1
:docs-asm-ssm-url-3_0_0: xref:spring-security-module::index.adoc#_3_0_0_release

:docs-spring-boot: xref:across-autoconfigure::index.adoc#spring-boot
:docs-across-spring-compatibility-ax-conf: xref:across-autoconfigure::index.adoc#across-configuration
:docs-across-core-events: {docs-across-base-url}developing-modules:events.adoc
:docs-across-web-menus: {docs-across-base-url}across-web:web-views/working-with-menus.adoc

:!numbered:

[abstract]
--
Platform 5.1.0 is bound to Across 5.1.0.
Upgrading to Platform 2.1.0 usually requires you to make some configuration and code changes to your applications.

NOTE: This guide is not a full overview of all new features and changes in Across or any of its modules.
It mainly focuses on upgrade related changes: usually breaking changes or new features that impact application/module configuration.
--

== Across Core
=== Deprecated Spring Boot properties

* Some Spring Boot properties have been removed in Spring Boot 2.2 and 2.3, if you still use them you should migrate them
** `spring.http.encoding.* -> `server.servlet.encoding.*
** `spring.http.log-request-details` -> `spring.mvc.log-request-details (Spring MVC) or `spring.codec.log-request-details` (Spring WebFlux)
** `spring.http.converters.preferred-json-mapper` -> `spring.mvc.converters.preferred-json-mapper`
** `spring.http.multipart.enabled` -> `spring.servlet.multipart.enabled`

=== HttpHiddenMethodFilter

If you are using the `HttpHiddenMethodFilter` in your project, you must manually reinclude it. It has been removed from Spring Boot 2.3 as a default inclusion. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes)

=== Empty @RestController logic change

Since Spring Framework 5.2 a change has been made in how `@RestController()` (without explicit mapping) behaves.

The following example might not behave like before:

```
@RestController
class PersonController {

    @GetMapping
    @ResponseBody
    public String getPerson() {
       return "Joe";
    }

}
```

Before Spring Framework 5.2 an empty `@RestController` would automatically match `**`. This has been change this Spring Framework 5.2 because it was behaving as default `@RequestMapping()` endpoint. The change was done in https://github.com/spring-projects/spring-framework/issues/22543 and is a breaking change.

You should scan occurences of empty `@RestController` annotations and explicitly match them with `@RequestMapping("****")`. This is a common scenario if you are using *CustomRequestMapping* or *RequestCondition*

The above controller should look like:

```
@RestController
@RequestMapping("**")
class PersonController {

    @GetMapping
    @ResponseBody
    public String getPerson() {
        return "Joe";
    }

}
```
