= Migration guide: platform 2.1.x to 4.0.x

[abstract]
--
Platform 3.0.0 binds to Across 4.0.0, which is built on top of Spring Boot 2.0.x and Spring Framework 5.0.x.
This is a major upgrade with *a lot of breaking changes*, mostly due to changes inside Spring dependencies.

NOTE: This guide is not a full overview of all new features and changes in Across or any of its modules.
It mainly focuses on upgrade related changes: usually breaking changes or new features that impact application/module configuration.
--

== State of the migration guide

Current Platform development version is `3.0.0-SNAPSHOT`, slated to become `3.0.0.M2`.




[abstract]
--
Platform 4 binds to Across 5.0.0, with Spring Boot 2.1.
4.0.x may supersede Platform 3.0.x upon final release.
--

== State of the migration guide

Current Platform development version is `4.0.0-SNAPSHOT`, slated to become `4.0.0.M1`.

== Migration steps

First follow all steps as described in xref:platform-2-1-to-3-0.adoc[Migration guide: platform 2.1.x to 3.0.x].

== Breaking changes



