= Across platform BOM
Across platform BOM does not exist anymore and is replaced by the following three parent poms:

* Across platform dependencies
* Across application parent
* Across module parent

== Maven properties
We introduced a couple of maven properties to simplify the pom configuration.
The following properties where introduced:

* `revision`: 5.0.0.RELEASE
* `maven.deploy.skip`: default value is false

== Across platform dependencies
The across parent dependency contains all dependency versions of across standard modules that work together for a specific version of across.
This should never be used directly in your own application or module, you should use the more specific application and module parents.

[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.foreach.across</groupId>
            <artifactId>across-application-parent</artifactId>
            <version>${revision}</version>
            <packaging>pom</packaging>
        </dependency>
    </dependencies>
</dependencyManagement>
----


== Across application parent
A parent that needs to be used when creating a custom across application.

[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.foreach.across</groupId>
            <artifactId>across-application-parent</artifactId>
            <version>${revision}</version>
            <packaging>pom</packaging>
        </dependency>
    </dependencies>
</dependencyManagement>
----

== Across module parent
A parent pom that will used for building across modules.

[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.foreach.across</groupId>
	        <artifactId>across-module-parent</artifactId>
            <version>${revision}</version>
            <packaging>pom</packaging>
        </dependency>
    </dependencies>
</dependencyManagement>
----
