:docs-spring-boot: https://across-docs.foreach.be/across/3.0.0-SNAPSHOT/reference/spring-boot.html#spring-boot

=== 2.0.x to 2.1.x
This migration guide describes the most common steps necessary when upgrading from Platform BOM 2.0.x to 2.1.x.
Platform 2.1.x is bound to Across 3.x, which is the first release with the `across-autoconfigure` artifact and builds more on top of Spring Boot.

Upgrading to Platform 2.1.x usually requires you to make some configuration and code changes to your applications.

NOTE: This guide is not a full overview of all new features and changes in Across or any of its modules.
It mainly focuses upgrade related changes: usually breaking changes or new features that impact application/module configuration.

=== Auto-configuration support

==== Add autoconfigure artifact
When upgrading your applications (built with `@AcrossApplication`), the first step is to add the new `across-autoconfigure` artifact to your project.

[source,xml,indent=0]
----
<dependencies>
    <dependency>
        <groupId>com.foreach.across</groupId>
        <artifactId>across-autoconfigure</artifactId>
    </dependency>
</dependencies>
----

The new autoconfigure artifact contains compatibility configuration for many Spring Boot starters.
Adding it to your project allows you to rely more on the starters and to remove some previously required configuration imports.

Please see the {docs-spring-boot}[Spring Boot compatibility documentation] for a detailed list of starters that are now supported.

Some useful additions now available without additional configuration:

* Websocket support (built-in with AcrossWebModule-
* Spring Data web support
* Actuator support
* Spring Boot Admin (& client) support
* Spring Session support
* Swagger2 support

:!numbered:
===== Cleanup @AcrossApplication
Review the release notes and Spring Boot compatibility documentation and remove imports and annotations from your `@AcrossApplication` class.

.Example @AcrossApplication configuration cleanup
[source,java]
----
// Across Platform 2.0.x
@AcrossApplication(
    modules = { ... }
    scan = { AcrossPlatform.PACKAGE, "my.custom.modules"}
)
@EnableSpringDataWebSupport
@Import( DataSourceAutoConfiguration.class )
public class MyApplication
{
}

// Across Platform 2.1.x - with across-autoconfigure
@AcrossApplication( modules = { ... } )
public class MyApplication
{
}
----

If you have any of the following annotations in any of your modules or on your application class, they can just be removed:

* `@EnableSpringDataWebSupport`
* `@EnableWebSocket`
* `@EnableWebSocketMessageBroker`

=== Configuration validation
new error messages


=== Event handling changes

==== `AcrossLifecycleListener`

=== @ModuleConfiguration changes

=== Deprecations

* `StringToDateConverter
* `@AcrossDepends` on annotated classes -> `@ConditionalOnAcrossModule`
* `AcrossEvent`, `@Event`, `@EventName`, `AcrossEventPublisher`

=== Important Across Web changes

==== PrefixingHandlerMappingConfigurer
==== Menu building

=== Standard module changes
The following section applies to the breaking changes in the standard modules.
These instructions are only relevant if you use these modules in your applications.

==== AcrossHibernateJpaModule

==== SpringSecurityModule

==== BootstrapUiModule

==== EntityModule
message codes on form group
addition of `EntityAdminMenu`and `EntityAdminMenuEvent`


