[[whats-new]]
= Migration guide: platform 2.0.x to 2.1.x
:toc: left
:toclevels: 3
:sectnums:
:chapter-number: 0
:docinfo1:

:docs-across-base-url: https://across-docs.foreach.be/across/3.0.0-SNAPSHOT/reference
:docs-spring-boot: {docs-across-base-url}/spring-boot.html#spring-boot
:docs-across-core: {docs-across-base-url}/index.html
:docs-across-core-events: {docs-across-base-url}/developing-applications.html#events

:!numbered:

[abstract]
This migration guide describes the most common steps necessary when upgrading from Platform BOM 2.0.x to 2.1.x.

== Migrating to 2.1.0
Platform 2.1.0 is bound to Across 3.0.0, which is the first release with the `across-autoconfigure` artifact and builds more on top of Spring Boot.
Upgrading to Platform 2.1.0 usually requires you to make some configuration and code changes to your applications.

NOTE: This guide is not a full overview of all new features and changes in Across or any of its modules.
It mainly focuses upgrade related changes: usually breaking changes or new features that impact application/module configuration.

=== Across Core
==== Auto-configuration support
===== Add autoconfigure artifact
When upgrading your applications (built with `@AcrossApplication`), the first step is to add the new `across-autoconfigure` artifact to your project.

[source,xml,indent=0]
----
<dependencies>
    <dependency>
        <groupId>com.foreach.across</groupId>
        <artifactId>across-autoconfigure</artifactId>
    </dependency>
</dependencies>
----

The new autoconfigure artifact contains compatibility configuration for many Spring Boot starters.
Adding it to your project allows you to rely more on the starters and to remove some previously required configuration imports.

Please see the {docs-spring-boot}[Spring Boot compatibility documentation] for a detailed list of starters that are now supported.

Some useful additions now available without additional configuration:

* Websocket support (built-in with AcrossWebModule)
* Spring Data web support
* Actuator support
* Spring Boot Admin (& client) support
* Spring Session support
* Swagger2 support

===== Cleanup @AcrossApplication
Review the release notes and Spring Boot compatibility documentation and remove imports and annotations from your `@AcrossApplication` class.

.Example @AcrossApplication configuration cleanup
[source,java]
----
// Across Platform 2.0.x
@AcrossApplication(
    modules = { ... },
    modulePackages = { "my.custom.modules" },
    modulePackageClasses = { AcrossPlatform.class } <1>
)
@EnableSpringDataWebSupport <2>
@Import( DataSourceAutoConfiguration.class )
public class MyApplication
{
}

// Across Platform 2.1.x - with across-autoconfigure
@AcrossApplication( modules = { ... } )
public class MyApplication
{
}
----

<1> It is no longer to include the default Across standard modules packages when you want to add your own packages for module scanning.
The default standard modules package will always be included.

<2> Several annotations and configuration imports can simply be dropped as `across-autoconfigure` takes care of the configuration now.

If you have any of the following annotations in any of your modules or on your application class, they can just be removed when you have the right starters on the classpath:

* `@EnableSpringDataWebSupport`
* `@EnableWebSocket`
* `@EnableWebSocketMessageBroker`

===== META-INF/across.configuration
Across 3.0.0 externalizes some of its configuration in a `META-INF/across.configuration` properties file.
This is especially used for auto-configuration and configuration validation settings.

Please see the link:{docs-across-core}[Across reference documentation] for a full description of the configuration file and what you can do with it.

==== Configuration validation
Across now attempts to validate your configuration when starting.
It will check for the presence of configuration classes in places where they should not be.
This could be using a configuration class on either the application level or in a module, where a different module already handles that particular bit of configuration.

Bootstrapping your application with a bad configuration will fail.

.Better error messages
One of the additions in Across 3.0.0 is the new failure analyzers.
When you are using `@AcrossApplication` and executing as a Spring Boot application, you should receive a more readable error messages with specific information on the problem.

.@ComponentScan on your application configuration
An example is that bootstrapping will fail if a `@ComponentScan` is detected on your `@AcrossApplication` class, where that component scan would conflict with the application module package.
It is possible that in certain applications this would not cause an actual problem, it is however still considered a bad practice and an invalid configuration.

.Disabling configuration validation
You can disable configuration validation - for example in production - by setting the property `across.configuration.validate` to `false`.
We strongly advise you to leave it on during development mode as it can help you avoid common configuration mistakes.

.Adding configuration validation
It's possible to configure your own illegal configurations in the `META-INF/across.configuration` file.
This is especially useful for shared modules that activate application-level features.

==== New event handling
The internal event handling system has been entirely rewritten and now builds on top of the default Spring Framework event handling infrastructure.
Instead of the Across-specific `@Event`, the Spring Framework `@EventListener` should now be used.

Apart from how events are treated internally, there is no difference anymore in handling Across specific or regular Spring Framework events.

Most old event related classes have simply been deprecated, and breaking changes kept as limited as possible.
In simple applications no changes would be required for this release.

.Example @Event to @EventListener
[source,java]
----
// Across Platform 2.0.x
@Event
public void handle( @EventName("eventName") MyEvent myEvent ) {
}

// Across Platform 2.1.x
@EventListener(condition = "#myEvent.eventName == 'myEvent'")
public void handle( MyEvent myEvent ) {
    // Called if the event is of type MyEvent
    // and property 'eventName' has the value 'myEvent'
}
----

See the <<deprecations,deprecations>> section for a list of the event-related deprecations and how to replace them.

.New available features
Due to this refactoring some new features are now also available:

* using `@TransactionalEventListener`
* explicitly order individual event handler methods using `@Order` or `@OrderInModule`
* event listener methods can have a return value which will be published as a new event

Please read the link:{docs-across-core-events}[Across reference documentation section] for a full overview of all features.

.Removal of MBassador dependency
The MBassador dependency - responsible for the previous event bus implementation - has been removed entirely.
Any listener methods that were directly using MBassador annotations will have to be rewritten as an `@EventListener`.

===== Across bootstrap events
One of the breaking changes with the new event handling infrastructure is that it is no longer possible to use regular `@Event` (or `@EventListener`) to intercept Across bootstrap related events from the parent application class.
If you want to handle bootstrap related events from a parent `ApplicationContext`, you should do so in a component implementing the `AcrossLifecycleListener` interface.

NOTE: Using `AcrossLifecycleListener` to modify the Across context configuration from a parent `ApplicationContext` (eg the `@AcrossApplication` class) is not required.
Instead you can use the `AcrossBootstrapConfigurer` interface on one ore more of your components, which was introduced especially for this purpose.

==== @ModuleConfiguration
The internal processing of `@ModuleConfiguration` classes - module extensions provided by other modules - has been changed.
This was necessary to fix issues with incorrect handling of conditionals on these `@ModuleConfiguration` classes.

This introduces some possibly breaking changes:

* `@ModuleConfiguration` classes are now always `@Configuration` classes as well, this means they would also be processed by regular component scans, where in the past they might not have been
* `@ModuleConfiguration` classes are only scanned for in the `extensions` package, any `@ModuleConfiguration` class in a `config` package will now be loaded in the original module, instead of correctly treated as a module configuration extension
* import order has changed: module extensions will now always be imported before any other annotated classes (and before any injected Spring Boot auto-configuration classes)

==== New conditionals
Across 3.0.0 introduces some new conditionals:

`@ConditionalOnAcrossModule`::
  Use this annotation when you want to check for the presence or absence of a specific Across module.
  This replaces the use of `@AcrossDepends` on regular components.
  `@AcrossDepends` should now only be used on module descriptors, and you will see a warning printed when it is used on components.

`@ConditionalOnAutoConfiguration`::
  Use this conditional if you want to check if an auto-configuration class has been loaded anywhere in the Across application.

==== AcrossModule component scan
The default `AcrossModule` still only scans the `config` package by default.
However, a very common case is the behaviour of the dynamic modules: all child packages are scanned for components, with the exception of `extensions` and `installers`.
The former contains components for module extensions, the latter installers and related components.

A new helper method has been added to quickly configure an Across module with this behaviour.

.Example AcrossModule scanning all child packages
[source,java]
----
MyModule extends AcrossModule {
    public static final String NAME = "MyModule";

    @Override
    public String getName() {
        return NAME;
    }

    @Override
    protected void registerDefaultApplicationContextConfigurers( Set<ApplicationContextConfigurer> contextConfigurers ) {
        contextConfigurers.add( ComponentScanConfigurer.forAcrossModule( MyModule.class ) );
    }
}
----

[[deprecations]]
==== Deprecations
The following is a list of classes that have been deprecated in Across 3.0.0:

`StringToDateConverter`::
  A replacement implementation `StringToDateTimeConverter` is available that also supports the Java 8 time implementations.

`AcrossEvent`::
  It is not required anymore for an event type to implement this marker interface.

`@Event`::
  Use the Spring Framework `@EventListener` instead.

`@EventName`::
  Use a `conditional` attribute on your `@EventListener` instead.

`ParameterizedAcrossEvent`::
  Implement the Spring Framework `ResolvableTypeProvider` interface instead.

`AcrossEventPublisher`::
  Use the Spring Framework `ApplicationEventPublisher` instead.

=== Across Web

==== PrefixingHandlerMappingConfigurer
==== Menu building

=== Across Standard Modules
The following section applies to the breaking changes in the standard modules.
These instructions are only relevant if you use these modules in your applications.

==== AcrossHibernateJpaModule

==== SpringSecurityModule

==== BootstrapUiModule

==== EntityModule
message codes on form group
addition of `EntityAdminMenu`and `EntityAdminMenuEvent`


